## 谈谈Java中的异常吧

在Java中，异常是程序在执行过程中由于某些原因而中断的一种特殊情况。Java通过使用异常提供了一种强制的错误处理机制，使得错误处理代码可以与正常的代码逻辑分离，提高了代码的可读性和可维护性。

Java的异常分为两大类：**检查型异常**（Checked Exception）和**运行时异常**（Runtime Exception）。

1. **检查型异常**：这类异常在编译时就需要被处理（即必须被捕获或者声明抛出），否则编译器会报错。这类异常通常是由外部错误引起的，如文件不存在、网络连接失败等。

2. **运行时异常**：这类异常在编译时不需要被处理，它们通常由程序逻辑错误引起，如空指针访问、数组越界等。

Java处理异常的主要方式是**try-catch-finally**语句块和**throws**关键字。

- **try-catch-finally**：`try`块包含可能抛出异常的代码，`catch`块用于捕获和处理异常，`finally`块包含无论是否发生异常都需要执行的代码。

- **throws**：如果一个方法不能或不想处理某个检查型异常，可以在方法签名中使用`throws`关键字声明该异常，这样该异常就会被抛给该方法的调用者处理。

此外，Java还支持自定义异常，我们可以通过继承`Exception`类或其子类来创建自定义的检查型异常，通过继承`RuntimeException`类来创建自定义的运行时异常。

## Exception 和 Error 有什么区别？

`Exception`和`Error`都是继承自`Throwable`类的两个子类：

1. **Exception**：`Exception`类及其子类用于表示程序可以处理的异常，这些异常通常是由程序逻辑错误或外部资源问题引起的。例如，`IOException`（输入输出异常）、`SQLException`（数据库访问异常）等。`Exception`类又分为两种：检查型异常（Checked Exception）和运行时异常（Runtime Exception）。检查型异常在编译时就需要被处理，而运行时异常在编译时不需要被处理，它是程序逻辑⾃身的问题。

2. **Error**：`Error`类及其子类用于表示严重的问题，这些问题通常是由系统错误或资源耗尽等严重问题引起的，如`OutOfMemoryError`（内存溢出）、`StackOverflowError`（栈溢出）等。这些错误通常不应由程序来处理，而应当避免产生。一旦发生这类错误，Java虚拟机（JVM）没有办法恢复并正常运行。

总结：`Exception`是程序中应该捕获和处理的异常，而`Error`则是程序通常不应尝试捕获的严重问题。

## Checked Exception 和 Unchecked Exception 有什么区别？

1. **Checked Exception**：这类异常在编译时就需要被处理（即必须被捕获或者声明抛出），否则编译器会报错。这类异常通常是由外部错误引起的，如文件不存在、网络连接失败等。Checked Exception是`Exception`类及其子类（除了`RuntimeException`及其子类）。

2. **Unchecked Exception**：这类异常在编译时不需要被处理，它们通常由程序逻辑错误引起，如空指针访问、数组越界等。这些错误在编程时应该尽量避免。Unchecked Exception包括`RuntimeException`及其子类和`Error`类及其子类。

总结：`Checked Exception`是那些在编译时必须被处理的异常，而`Unchecked Exception`则是那些在运行时可能会抛出但在编译时不需要强制处理的异常。

## 如何处理异常

1. **捕获异常**：使用`try-catch-finally`语句块来捕获和处理异常。`try`块用于放置业务代码（可能会抛出异常）。`catch`块⽤于捕获并处理某个类型的异常，`finally`块则⽤于回收资源。当业务代码发⽣异常时，系统会创建⼀个异常对象，然后由`JVM`寻找可以处理这个异常的`catch`块，并将异常对象交给这个`catch`块处理。若业务代码打开了某项资源，则可以在`finally`块中关闭这项资源。

```java
try {
    // 业务代码（可能会抛出异常的代码）
} catch (ExceptionType1 e) {
    // 处理ExceptionType1类型的异常
} catch (ExceptionType2 e) {
    // 处理ExceptionType2类型的异常
} finally {
    // 无论是否发生异常，都会执行的代码（一般情况下，finally语句总会执行）
}
```

2. **声明抛出异常**：如果你的方法不想或不能处理某个检查型异常，你可以在方法签名中使用`throws`关键字声明该异常，这样该异常就会被抛给该方法的调用者处理。

```java
public void myMethod() throws ExceptionType1, ExceptionType2 {
    // 可能会抛出ExceptionType1或ExceptionType2的代码
}
```

> 备注：
>
> `Java 7` 引入了`try-with-resources`语句，可以自动管理资源，无需显式关闭。只要资源类实现了`AutoCloseable`或`Closeable`接口，就可以使用这个特性。
>
> ```java
> try (ResourceType resource = new ResourceType()) {
>  // 使用资源的代码
> } catch (Exception e) {
>  // 处理异常
> }
> ```

## finally总是会被执⾏嘛？

`finally`语句块中的代码几乎总是会被执行，无论`try`块中是否发生了异常，或者`try`和`catch`块中是否有`return`语句。这使得`finally`成为执行清理工作（如关闭文件、释放资源等）的理想位置。

然而，也有一些特殊情况下，`finally`块中的代码可能不会被执行：

1. 如果在`finally`语句块之前的代码使用了`System.exit()`来退出程序，或者发生了`JVM`错误，那么`finally`语句块中的代码将不会被执行。
2. 如果当前线程被其他线程中断或被`kill`，那么`finally`语句块可能不会执行。
3. 如果`try`块或`catch`块中的代码在执行过程中进入了无限循环，那么`finally`块也不会被执行。